version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    links:
      - elasticsearch
    ports:
      - 5601:5601
