version: '3'
services:

  influxdb:
    image: influxdb:latest
    volumes:
      - ./conf/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  grafana:
    image: grafana/grafana:latest
    links:
      - influxdb
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
